### ISSUE TITLE
Intern Test To-do

### ISSUE THREAD

**Issue by dahyeo-n** [dahyeo-n/intern-test#1]
## 어떤 기능인가요?

> 인증 및 인가와 JEST를 이용한 테스트 코드를 구현할 예정입니다.

### 작업 내용

- [x] 0. 메인 페이지, 마이 페이지
- [x] 1. 회원가입
- [x] 2. 로그인
- [x] 3. 권한별 라우팅 제어
- [x] 4. tailwind(styled-components)를 이용한 스타일링
- [x] 5. Zustand를 통한 Client-side 전역 State 관리
- [x] 6. Axios, Tanstack-query를 통한 외부통신 및 server-side 전역 state 관리
- [x] 7. Jest(Cypress, 자바스크립트 E2E 테스트 프레임워크)를 이용한 테스트
- [x] 8. Sentry 도입 및 로그 확인

### 세부 구현 사항 (1)

- [x] Vite + Typescript 기반 프로젝트 설치
- [x] Zustand, Tanstack-query, Tailwind css(또는 styled-components), React-router-dom 세팅
- [x] Vite에서의 환경변수 세팅 및 폴더 구조 구성하기
- [x] JSON Placeholder를 이용하여 외부 통신 테스트
  - [x] 반드시 Tanstack-query를 이용해서 API call → 캐싱 처리까지 테스트
  - [x] Tanstack-query DevTools를 활용하여 캐싱 확인
  - [x] 요청 목록 (각 항목에 대해 Query key 작성)
    - [x] 리스트 `https://jsonplaceholder.typicode.com/todos`
    - [x] 단건 `https://jsonplaceholder.typicode.com/todos/1`
- [x] 회원가입, 로그인, 마이페이지 컴포넌트 구현
  - 필수기능 : 회원가입, 로그인, 프로필 변경
  - Access Token 사용
- [x] tailwind(또는 Styled-components)를 이용한 스타일링
- [x] JWT 인증서버를 활용하여 Access Token 기반 페이지 권한 처리(라우팅 제어)

### 세부 구현 사항 (2)

- [x] Jest 기반 유닛 테스트 코드 작성 및 테스트
- [x] 유닛 테스트 2회 이상 수행하기
- [x]Sentry 기반 애플리케이션 에러 모니터링
- [x] Vercel을 이용한 배포
- [x] AI를 통해 코드 리뷰 받아보기 + 피드백 반영하여 개선하기
    - [x] 효율적인 코드, 보안상 위험한 코드 등에 대한 일괄 리팩토링
    - [x] Custom hooks 이용하기
    - [x] Vercel에 재배포하기
